apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: httpbin-rust-test
  namespace: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  # Define traffic selector match conditions
  # All conditions must evaluate to true for the plugin to be applied
  match:
    # Define the workload mode, valid options are: SERVER, CLIENT, CLIENT_AND_SERVER
    # CLIENT and SERVER are analogous to inbound and outbound traffic
    # Gateways should set CLIENT
    # Default is CLIENT_AND_SERVER
    - mode: SERVER
    # Define port numbers to match. If not specified, all ports are matched
    # If any one port matches, this condition evaluates to true
    - ports:
      - number: 80
  url: oci://docker.io/dhawton/wasm-rust-test:v1
  imagePullPolicy: Always