apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: httpbin-rust-test
  namespace: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  match:
    - mode: SERVER
    - ports:
      - number: 80
  url: oci://docker.io/dhawton/wasm-rust-test:v1